#!/bin/bash
# Update package lists
yum update -y
wait

# Install system dependencies
yum install -y git
wait
yum install -y unixODBC
wait
yum install -y python3.9-pip
wait

# Clone the repository
cd /home/ec2-user
mkdir -p my-python
git clone https://github.com/muruganpm/pythonapp.git ./my-python
wait
cd /home/ec2-user/my-python/

# Install Python dependencies
pip3.9 install --no-cache-dir --upgrade pip setuptools wheel
wait
pip3.9 install --no-cache-dir -r requirements.txt
wait

# Fix ownership and permissions
chown -R ec2-user:ec2-user /home/ec2-user/my-python
chmod -R 755 /home/ec2-user/my-python

# Configure firewall
sudo firewall-cmd --add-port=5000/tcp --permanent
sudo firewall-cmd --reload
wait

# Create the systemd service file
cat <<EOF > /etc/systemd/system/my-python-app.service
[Unit]
Description=My Python Application
After=network.target

[Service]
User=ec2-user
WorkingDirectory=/home/ec2-user/my-python/
ExecStart=/usr/bin/python3.9 /home/ec2-user/my-python/app.py
Restart=always

[Install]
WantedBy=multi-user.target
EOF
wait

# Fix service file permissions
chown ec2-user:ec2-user /etc/systemd/system/my-python-app.service
chmod 644 /etc/systemd/system/my-python-app.service
wait

# Enable and start the service
systemctl daemon-reload
wait
systemctl enable my-python-app.service
wait
systemctl start my-python-app.service
wait
systemctl status my-python-app.service
